name: evaluator
channels:
    - conda-forge
dependencies:
    # Base depends
    - pip
    - python =3.7
    - setuptools

    # Sphinx specific
    - nbsphinx
    - sphinxcontrib-bibtex
    - pandoc
    - ipython

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - networkx
    - pint >=0.10.1
    - uncertainties

    - pip:
        - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
